#!/usr/bin/env python3
"""Submit staging, unit preparation, CV fits, and per-unit aggregation from a login node."""
import argparse
from datetime import datetime
import json
import math
import os
from pathlib import Path
import subprocess
import sys

SOURCE = '/exports/cmvm/datastore/sbms/groups/INCR-NolanLab/ActiveProjects/Yiming/NWR1/processed'
SCRATCH = '/exports/eddie/scratch/s2155699/ephys/glm_hmm'
def write_json(path, data):
    path = Path(path)
    temporary = path.with_suffix(path.suffix + '.tmp')
    temporary.write_text(json.dumps(data, indent=2, allow_nan=False) + '\n')
    temporary.replace(path)


def select_files(path, mice, days, unit_ids=None):
    """Read the file-per-row inventory generated by ramps/prepare_nwb_units.py."""
    result = []
    for line in Path(path).read_text().splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row['session_type'] != 'VR':
            continue
        if mice is not None and int(row['mouse'][1:]) not in mice:
            continue
        if days is not None and int(row['day'][1:]) not in days:
            continue
        selected = [i for i in row['unit_ids'] if unit_ids is None or i in unit_ids]
        if selected:
            result.append(dict(row, selected_unit_ids=selected))
    if not result:
        raise ValueError('No VR units match the selection')
    return result


def stage(run):
    """Only this staging-queue entry point accesses DataStore."""
    import h5py
    config = json.loads((run/'config.json').read_text())
    if (run/'staging_complete.json').exists():
        raise RuntimeError('Run already staged')
    for row in json.loads((run/'files.json').read_text()):
        source = Path(config['source']) / row['relative_path']
        target = run/'input'/row['relative_path']
        target.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(['rsync', '-rt', '--no-perms', '--no-owner', '--no-group',
                        '--chmod=Du+rwx,Fu+rw', str(source), str(target)], check=True)
        with h5py.File(target, 'r') as f:
            ids = [int(i) for i in f['units/id'][:]]
        if ids != row['unit_ids']:
            raise RuntimeError(f'Unit IDs changed; regenerate the inventory: {source}')
    write_json(run/'staging_complete.json', {'complete': True})


def worker(run, phase, index):
    """A batch contains several folds, each in a fresh Python process."""
    config = json.loads((run/'config.json').read_text())
    units = [json.loads(line) for line in (run/'units.jsonl').read_text().splitlines()]
    if not (run/'staging_complete.json').exists():
        raise RuntimeError('Staging failed; analysis will not start')
    fits = config['fit_count']
    batches = math.ceil(fits / config['fits_per_task'])
    unit_index, batch = divmod(index-1, batches) if phase == 'fit' else (index-1, None)
    unit = units[unit_index]
    folder = run/unit['output']
    folder.mkdir(parents=True, exist_ok=True)
    script = Path(__file__).with_name('glm_hmm_sklearn.py')
    base = [config['python'], '-u', str(script)]
    data = str(folder/'data.npz')
    if phase == 'prepare':
        subprocess.run(base + ['prepare', '--nwb-file', str(run/'input'/unit['relative_path']),
                               '--unit-index', str(unit['unit_id']), '--bin-size', str(config['bin_size']),
                               '--data-file', data], check=True)
        write_json(folder/'prepared.json', {'unit_id': unit['unit_id']})
        return

    if not (folder/'prepared.json').exists():
        raise RuntimeError(f'Unit preparation failed: {folder}')
    arguments = ['--data-file', data, '--results-dir', str(folder/'cv_results')] + config['grid_args']
    if phase == 'fit':
        for fit in range(batch*config['fits_per_task']+1, min((batch+1)*config['fits_per_task'], fits)+1):
            if (folder/'cv_results'/f'task_{fit:05d}.json').exists():
                continue
            subprocess.run(base + ['fit-task', '--task-id', str(fit)] + arguments, check=True)
    else:
        subprocess.run(base + ['aggregate', '--output-dir', str(folder)] + arguments, check=True)
        write_json(folder/'complete.json', {'unit_id': unit['unit_id']})


def submit(run, phase, count, hold, config, jobs):
    """Split large arrays into dependent waves; concurrency stays globally bounded."""
    scripts = Path(__file__).resolve().parent
    for offset in range(0, count, config['array_limit']):
        size = min(config['array_limit'], count-offset)
        command = ['qsub', '-terse', '-N', f'glmhmm_{phase}',
                   '-o', str(run/'logs'), '-e', str(run/'logs')]
        if hold:
            command += ['-hold_jid', hold]
        if phase != 'stage':
            command += ['-t', f'1-{size}', '-tc', str(config['max_parallel']),
                        '-l', f"h_rss={config['memory']},h_rt={config['runtime']}"]
        command += [str(scripts/('stage_glm_hmm_sklearn.sh' if phase == 'stage' else 'run_glm_hmm_sklearn.sh')),
                    str(scripts), str(run), config['python'], phase, str(offset)]
        response = subprocess.check_output(command, text=True).strip()
        hold = response.split('.')[0]
        jobs.append(dict(phase=phase, job_id=hold, offset=offset, count=size))
        write_json(run/'jobs.json', jobs)
        print(f'{phase}: job {response}, offset {offset}', flush=True)
    return hold


def main():
    from glm_hmm_sklearn import add_grid_arguments, DEFAULT_BIN_SIZE, DEFAULT_UNIT_JSONL_PATH

    grid_parser = argparse.ArgumentParser(add_help=False, allow_abbrev=False)
    add_grid_arguments(grid_parser)
    p = argparse.ArgumentParser(description=__doc__, parents=[grid_parser], allow_abbrev=False)
    p.add_argument('--unit-manifest', type=Path, default=Path(DEFAULT_UNIT_JSONL_PATH))
    p.add_argument('--mice')
    p.add_argument('--days')
    p.add_argument('--all', action='store_true')
    p.add_argument('--units', help='Optional actual unit IDs, comma-separated; applies to each selected NWB')
    p.add_argument('--data-folder', default=SOURCE)
    p.add_argument('--output-dir', type=Path, default=Path(SCRATCH))
    p.add_argument('--bin-size', type=float, default=DEFAULT_BIN_SIZE)
    p.add_argument('--fits-per-task', type=int, default=2)
    p.add_argument('--max-parallel', type=int, default=500)
    p.add_argument('--array-limit', type=int, default=10000)
    p.add_argument('--memory', default='32G')
    p.add_argument('--runtime', default='9:59:59')
    p.add_argument('--plan-only', action='store_true')
    p.add_argument('--worker', choices=['stage','prepare','fit','aggregate'], help=argparse.SUPPRESS)
    p.add_argument('--run-dir', type=Path, help=argparse.SUPPRESS)
    p.add_argument('--index', type=int, help=argparse.SUPPRESS)
    a = p.parse_args()
    if a.worker:
        if a.worker == 'stage':
            stage(a.run_dir)
        else:
            worker(a.run_dir, a.worker, a.index)
        return
    if not a.unit_manifest or (a.all and (a.mice or a.days)) or (not a.all and not (a.mice and a.days)):
        p.error('Supply --unit-manifest and either --all or both --mice and --days')
    def ids(text, prefix):
        return None if text is None else {int(s.strip().upper().removeprefix(prefix)) for s in text.split(',')}
    selected = select_files(a.unit_manifest, ids(a.mice,'M'), ids(a.days,'D'), ids(a.units,''))
    run = a.output_dir.resolve()/datetime.now().strftime('run_%Y%m%d_%H%M%S_%f')
    run.mkdir(parents=True)
    (run/'logs').mkdir()
    config = {k:v for k,v in vars(a).items() if k not in ('worker','run_dir','index','unit_manifest','output_dir')}
    config.update(source=os.path.abspath(a.data_folder), python=sys.executable)
    grid_options = {name: getattr(a, name) for name in vars(grid_parser.parse_args([]))}
    config['grid_args'] = [item for name, value in grid_options.items()
                           for item in ('--' + name.replace('_', '-'), str(value))]
    # The analysis script owns the model grid. The launcher only asks for its size.
    response = subprocess.check_output(
        [sys.executable, str(Path(__file__).with_name('glm_hmm_sklearn.py')), 'task-count']
        + config['grid_args'], text=True)
    config['fit_count'] = int(response.strip().splitlines()[-1])
    write_json(run/'config.json', config)
    write_json(run/'files.json', selected)
    units = []
    for row in selected:
        for unit_id in row['selected_unit_ids']:
            units.append(dict(task_id=len(units)+1, relative_path=row['relative_path'],
                              unit_id=unit_id, mouse=row['mouse'], day=row['day'],
                              experiment=row['experiment'],
                              output=str(Path('units')/row['relative_path']/f'unit_{unit_id}')))
    (run/'units.jsonl').write_text(''.join(json.dumps(u)+'\n' for u in units))
    fits = config['fit_count']
    batch_count = len(units)*math.ceil(fits/a.fits_per_task)
    print(f'Run: {run}\n{len(selected)} NWBs; {len(units)} units; {fits // a.cv_folds} candidates; '
          f'{fits} CV fits/unit; {batch_count} fit-array tasks', flush=True)
    if a.plan_only:
        return
    jobs=[]
    hold=submit(run,'stage',1,None,config,jobs)
    hold=submit(run,'prepare',len(units),hold,config,jobs)
    hold=submit(run,'fit',batch_count,hold,config,jobs)
    submit(run,'aggregate',len(units),hold,config,jobs)


if __name__ == '__main__':
    main()
